# Exercises
1. Import numpy as np
1. create 10 zeroes
1. create a vector with values ranging from 10 to 100
1. reverse it
1. reshape it to a 3x30
1. Create the vector with elems 1,2,9,0,0,1,4,0. Find indices of non-zero elems.
1. Create a 3x3 identity matrix
1. Create a random vector of size 50 with values uniformely distributed in (-1, 1). Find the average of these values.
1. create a 5x5 matrix with 1,2,3,4 just below the 1st diag and 0 in rest.
1. Create a 5x3 matrix and a 3x4 one. Multiply them. 
1. Using the previous matrix, extract a new one with just the integer part of the values. Find at least 4 methods of doing this.
1. Create a random vector of size 25. Sort it.
1. Create a random 7x2 matrix representing 7 2D points. Convert them to polar coordinates.
1. Generate a 10x10 matrix. Generate a single random number. Find the number in the matrix closest to it.

In [3]:
import numpy as np

In [3]:
A=np.zeros(10)
print(A)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [5]:
B=np.arange(10,100)
print(B)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [14]:
l=B.size
for i in range(0,l//2):
    aux=B[i]
    B[i]=B[l-1-i]
    B[l-1-i]=aux
print(B)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57
 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81
 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98 99]


In [15]:
C=B.reshape(3,30)
print(C)

[[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
  34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63
  64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93
  94 95 96 97 98 99]]


In [18]:
D=np.array([1,2,9,0,0,1,4,0])
nonzeroindices=[]
l=D.size
for i in range(0,l):
    if D[i]!=0:
        nonzeroindices.append(i)
list(nonzeroindices)

[0, 1, 2, 5, 6]

In [19]:
E=np.eye(3)
print(E)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [43]:
F=np.random.uniform(-1,1,50)
average=F.sum()/F.size
print(F)
print(average)

[-0.89655106  0.06190198 -0.66084571  0.76502722  0.56592226  0.14518171
 -0.67744076 -0.13928958  0.64747014  0.48727392  0.87727111 -0.12200515
 -0.51120328 -0.28651992 -0.3173374   0.60663015  0.14002362 -0.76811004
 -0.44788606  0.18539159  0.70863788 -0.1788367   0.24183172  0.5978186
 -0.2170587   0.83248108  0.75918796 -0.26858669  0.61585719 -0.90716957
 -0.72491214  0.85062937 -0.85335463  0.05606325  0.89803356  0.96391429
 -0.29531881  0.11294143 -0.63480831 -0.32079021  0.5751408   0.4939932
  0.08806715 -0.33802125  0.84147768 -0.07056039  0.70771427 -0.17896638
 -0.68780751  0.41884554]
0.07482696841705039


In [35]:
AUX=np.matrix([1,2,3,4])
H=np.diagflat(AUX,-1)
print(H)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


In [4]:
A1=np.random.rand(5,3)
A2=np.random.rand(3,4)
I=np.dot(A1,A2)
print(I)

[[0.98970701 0.96448038 0.20184158 0.69057957]
 [0.65098453 0.53864759 0.17956372 0.40859396]
 [1.33595519 1.22697972 0.74655043 0.51046434]
 [1.46426738 1.38538282 0.75090595 0.62075518]
 [1.42299276 1.22179124 0.79299813 0.54179217]]


In [26]:
import math
J1=I
for i in range(0,5):
    for j in range(0,4):
        J1[i][j]=math.floor(I[i][j])
print(J1)
J2=I
for i in range(0,5):
    for j in range(0,4):
        if I[i][j]!=math.trunc(I[i][j]):
            if I[i][j]>=0:
                J2[i][j]=math.trunc(I[i][j])
            else:
                J2[i][j]=math.trunc(I[i][j])-1
        else:
            J2[i][j]=math.trunc(I[i][j])
print(J2)
J3=I
for i in range(0,5):
    for j in range(0,4):
        c=math.modf(I[i][j])[1]
        if c!=I[i][j]:
            if I[i][j]>=0:
                J3[i][j]=c
            else:
                J3[i][j]=c-1
        else:
            J3[i][j]=c
print(J3)
J4=I
for i in range(0,5):
    for j in range(0,4):
        J4[i][j]=int(I[i][j]//1)
print(J4)
J5=I
for i in range(0,5):
    for j in range(0,4):
        J5[i][j]=int(divmod(I[i][j],1)[0])
print(J5)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]
 [1. 1. 0. 0.]]


In [50]:
v=np.random.rand(25)
print(v)
v.sort()
print(v)

[0.88753754 0.13942576 0.7743082  0.05560733 0.45066226 0.96848762
 0.81395458 0.06431492 0.80487191 0.79051674 0.71606467 0.48599127
 0.71331677 0.5364959  0.37119885 0.34536535 0.39296723 0.42725586
 0.02364259 0.34723262 0.98539589 0.32691842 0.57782824 0.07524961
 0.65127192]
[0.02364259 0.05560733 0.06431492 0.07524961 0.13942576 0.32691842
 0.34536535 0.34723262 0.37119885 0.39296723 0.42725586 0.45066226
 0.48599127 0.5364959  0.57782824 0.65127192 0.71331677 0.71606467
 0.7743082  0.79051674 0.80487191 0.81395458 0.88753754 0.96848762
 0.98539589]


In [76]:
P=np.random.rand(7,2)
print(P)
def cart2polar(x,y):
    if x!=0:
        r=(x**2+y**2)**0.5
        ti=np.arctan2(1,y/x)
        if (r*np.cos(ti)!=x) or (r*np.sin(ti)!=y):
            theta=ti+3.141519
        else:
            theta=ti
    else:
        if y>0:
            theta=3.141519/2
        else:
            theta=3*3.141519/2
    if theta<0:
        theta+=2*3.141519
    v=[r,theta]
    return v
for i in range(0,7):
    v=cart2polar(P[i][0],P[i][1])
    P[i][0]=v[0]
    P[i][1]=v[1]
print(P)
    

[[0.32774021 0.72457248]
 [0.52941677 0.589394  ]
 [0.11619869 0.10567112]
 [0.34158472 0.07069565]
 [0.67805505 0.38236664]
 [0.92893775 0.01613845]
 [0.70797357 0.05990843]]
[[0.79524771 3.56630238]
 [0.79225464 3.8733604 ]
 [0.15706216 3.9743309 ]
 [0.34882373 4.50823293]
 [0.77843618 4.19885025]
 [0.92907792 4.69494405]
 [0.71050376 4.62789685]]


In [80]:
M=np.random.rand(10,10);
x=np.random.rand(1,1);
def absolute(y):
    if y>=0:
        return y
    else:
        return -y
d=-1
t=0
for i in range(0,10):
    for j in range(0,10):
        if absolute(x-M[i][j])<d:
            t=M[i][j]
print(M)
print(x)
print(t)


[[0.36694549 0.78051561 0.79775511 0.40821353 0.55361231 0.58856164
  0.60114662 0.23237742 0.41873976 0.41454483]
 [0.39982003 0.70103665 0.38638217 0.07011508 0.41863661 0.55132248
  0.82026434 0.8930564  0.71863913 0.65678828]
 [0.16406094 0.76276873 0.6023835  0.90148425 0.2120247  0.77690835
  0.2881073  0.42148967 0.3230994  0.08650378]
 [0.75218164 0.02396592 0.92333104 0.97833784 0.66647238 0.60202583
  0.73824375 0.73129073 0.57012501 0.83752759]
 [0.03679563 0.36615279 0.82204452 0.01297969 0.50722477 0.99732533
  0.68065174 0.94266007 0.72870126 0.96429183]
 [0.46126116 0.5725474  0.36358025 0.53320532 0.09133274 0.49805913
  0.20782866 0.70838485 0.42011129 0.77943941]
 [0.41474844 0.33806885 0.1332009  0.19918549 0.04563131 0.02287705
  0.28900763 0.85432946 0.48864464 0.53709826]
 [0.66467238 0.75988444 0.40302339 0.19146553 0.43954403 0.14458962
  0.81410891 0.70676453 0.11992632 0.55982243]
 [0.76504232 0.02608198 0.35132779 0.23680184 0.10625385 0.88537334
  0.84352189